### ISSUE TITLE
Student Projects page needs an alteration.

### ISSUE THREAD

**Issue by demiahmed** [demiahmed/uggradproposal#13]
THIS SHOULD BE DONE IN THE NEW BRANCH CREATED RECENTLY.

https://throwaway202007.wixsite.com/mockup/taiyo-farm

check this out. 

basically we are mixing the full and half width version to a create a new page. 

Discard both full and half and keep this as one project page standard in the new branch

**Comment by kavyavedagiri** [comment]
![image](https://user-images.githubusercontent.com/52077901/146683608-2e942bf0-f943-42e7-93a9-20237eec87ec.png)
