### ISSUE TITLE
People page width

### ISSUE THREAD

**Issue by demiahmed** [demiahmed/uggradproposal#20]
![image](https://user-images.githubusercontent.com/40930082/146344688-a0e213e0-8c84-43ca-b9b7-e51e7ca2bbca.png)

Make sure the page has uniform width. Top portion is wide whereas the projects one is narrow. Keep it consistent

**Comment by kavyavedagiri** [comment]
![image](https://user-images.githubusercontent.com/52077901/146683511-7cfeb379-4962-449d-a831-2fb0d96011b5.png)
alignment fixed
