### ISSUE TITLE
Homepage card size

### ISSUE THREAD

**Issue by demiahmed** [demiahmed/uggradproposal#7]
This card is way too huge. 

![image](https://user-images.githubusercontent.com/40930082/142817244-aa17e734-5787-445f-ad2b-d7972a4aa7ff.png)

set a fixed width and height for the image. dont let the size of the image disturb your UI grid. whatever size I supply the image, it should maintain the same aspect ratio and not go beyond the boundary.

**Comment by kavyavedagiri** [comment]
this issue has been corrected
